#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: splice_graphblas_bindings.py FALKORDB_ROOT GENERATED_RS")

root = Path(sys.argv[1]).resolve()
generated = Path(sys.argv[2]).resolve()
target = root / "graph/src/graph/graphblas/mod.rs"

src = target.read_text(encoding="utf-8")
new = generated.read_text(encoding="utf-8")

needle = '''#[derive(PartialEq, Copy, Clone, Hash, Debug, Default)]
#[repr(C)]
pub struct __BindgenComplex'''
idx = src.find(needle)
if idx < 0:
    raise RuntimeError("Could not locate generated-binding boundary in graphblas/mod.rs")

clean = []
for line in new.splitlines():
    if line.startswith("#!["):
        continue
    if line.startswith("/* automatically generated by rust-bindgen"):
        continue
    clean.append(line)

target.write_text(src[:idx] + "\n" + "\n".join(clean) + "\n", encoding="utf-8")
print("Installed Windows GraphBLAS bindings:", target)
