#!/usr/bin/env python3
"""Compare two Destiny 1 Ghidra code-graph exports.

Matches are intentionally tiered:
- PROVEN: unique exact instruction-byte fingerprint match
- STRONGLY_SUPPORTED: unique mnemonic-sequence + instruction-count match
- CANDIDATE: unique non-autogenerated function-name match

No raw offset is transferred merely because two versions use the same title ID.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

AUTO_NAME_RE = re.compile(r"^(FUN|LAB|SUB|thunk_FUN)_[0-9A-Fa-f]+$")


def load(path: Path) -> dict[str, Any]:
    doc = json.loads(path.read_text(encoding="utf-8"))
    if doc.get("schema") != "d1_ghidra_code_graph/v1":
        raise ValueError(f"{path}: unsupported schema {doc.get('schema')!r}")
    return doc


def fn_key(fn: dict[str, Any]) -> tuple[Any, ...]:
    return (fn.get("entry"), fn.get("image_offset"), fn.get("name"))


def index_unique(
    functions: list[dict[str, Any]],
    key_fn,
) -> dict[Any, dict[str, Any]]:
    buckets: dict[Any, list[dict[str, Any]]] = defaultdict(list)
    for fn in functions:
        key = key_fn(fn)
        if key is None:
            continue
        buckets[key].append(fn)
    return {key: values[0] for key, values in buckets.items() if len(values) == 1}


def exact_key(fn: dict[str, Any]):
    count = fn.get("instruction_count")
    digest = fn.get("instruction_bytes_sha256")
    if not isinstance(count, int) or count <= 0:
        return None
    if not isinstance(digest, str) or len(digest) != 64:
        return None
    return (count, digest)


def mnemonic_key(fn: dict[str, Any]):
    count = fn.get("instruction_count")
    digest = fn.get("mnemonic_sequence_sha256")
    if not isinstance(count, int) or count <= 0:
        return None
    if not isinstance(digest, str) or len(digest) != 64:
        return None
    return (count, digest)


def name_key(fn: dict[str, Any]):
    name = fn.get("name")
    if not isinstance(name, str) or not name or AUTO_NAME_RE.match(name):
        return None
    return name


def function_contains_offset(fn: dict[str, Any], offset: int) -> bool:
    ranges = fn.get("body_ranges")
    if not isinstance(ranges, list):
        return False
    for item in ranges:
        if not isinstance(item, dict):
            continue
        lo = item.get("min_image_offset")
        hi = item.get("max_image_offset")
        if isinstance(lo, int) and isinstance(hi, int) and lo <= offset <= hi:
            return True
    return False


def brief(fn: dict[str, Any]) -> dict[str, Any]:
    return {
        "entry": fn.get("entry"),
        "image_offset": fn.get("image_offset"),
        "name": fn.get("name"),
        "instruction_count": fn.get("instruction_count"),
        "instruction_byte_count": fn.get("instruction_byte_count"),
        "instruction_bytes_sha256": fn.get("instruction_bytes_sha256"),
        "mnemonic_sequence_sha256": fn.get("mnemonic_sequence_sha256"),
    }


def compare(a: dict[str, Any], b: dict[str, Any], anchor_offsets: list[int]) -> dict[str, Any]:
    af = [x for x in a.get("functions", []) if isinstance(x, dict)]
    bf = [x for x in b.get("functions", []) if isinstance(x, dict)]

    matched_a: set[tuple[Any, ...]] = set()
    matched_b: set[tuple[Any, ...]] = set()
    matches: list[dict[str, Any]] = []

    def add_match(left: dict[str, Any], right: dict[str, Any], status: str, basis: str):
        ka = fn_key(left)
        kb = fn_key(right)
        if ka in matched_a or kb in matched_b:
            return
        matched_a.add(ka)
        matched_b.add(kb)
        matches.append(
            {
                "status": status,
                "basis": basis,
                "a": brief(left),
                "b": brief(right),
                "offset_delta": (
                    right.get("image_offset") - left.get("image_offset")
                    if isinstance(left.get("image_offset"), int)
                    and isinstance(right.get("image_offset"), int)
                    else None
                ),
            }
        )

    a_exact = index_unique(af, exact_key)
    b_exact = index_unique(bf, exact_key)
    for key in sorted(set(a_exact) & set(b_exact), key=str):
        add_match(a_exact[key], b_exact[key], "PROVEN", "unique_exact_instruction_bytes")

    a_mn = index_unique(
        [fn for fn in af if fn_key(fn) not in matched_a], mnemonic_key
    )
    b_mn = index_unique(
        [fn for fn in bf if fn_key(fn) not in matched_b], mnemonic_key
    )
    for key in sorted(set(a_mn) & set(b_mn), key=str):
        add_match(
            a_mn[key],
            b_mn[key],
            "STRONGLY_SUPPORTED",
            "unique_mnemonic_sequence_and_instruction_count",
        )

    a_name = index_unique(
        [fn for fn in af if fn_key(fn) not in matched_a], name_key
    )
    b_name = index_unique(
        [fn for fn in bf if fn_key(fn) not in matched_b], name_key
    )
    for key in sorted(set(a_name) & set(b_name), key=str):
        add_match(a_name[key], b_name[key], "CANDIDATE", "unique_non_auto_function_name")

    anchors = []
    for offset in anchor_offsets:
        a_hits = [brief(fn) for fn in af if function_contains_offset(fn, offset)]
        b_hits = [brief(fn) for fn in bf if function_contains_offset(fn, offset)]
        anchors.append(
            {
                "image_offset": f"0x{offset:X}",
                "a_functions": a_hits,
                "b_functions": b_hits,
                "same_unique_exact_function": (
                    len(a_hits) == 1
                    and len(b_hits) == 1
                    and a_hits[0].get("instruction_bytes_sha256")
                    == b_hits[0].get("instruction_bytes_sha256")
                    and a_hits[0].get("instruction_count")
                    == b_hits[0].get("instruction_count")
                ),
            }
        )

    matches.sort(
        key=lambda row: (
            {"PROVEN": 0, "STRONGLY_SUPPORTED": 1, "CANDIDATE": 2}[row["status"]],
            row["a"].get("image_offset")
            if isinstance(row["a"].get("image_offset"), int)
            else 1 << 65,
        )
    )

    counts = {
        "a_functions": len(af),
        "b_functions": len(bf),
        "matched_total": len(matches),
        "proven_exact": sum(1 for m in matches if m["status"] == "PROVEN"),
        "strong_mnemonic": sum(
            1 for m in matches if m["status"] == "STRONGLY_SUPPORTED"
        ),
        "candidate_name": sum(1 for m in matches if m["status"] == "CANDIDATE"),
        "unmatched_a": len(af) - len(matched_a),
        "unmatched_b": len(bf) - len(matched_b),
    }

    return {
        "schema": "d1_executable_cross_version_compare/v1",
        "a_program": a.get("program"),
        "b_program": b.get("program"),
        "counts": counts,
        "anchor_checks": anchors,
        "matches": matches,
        "policy": {
            "exact_byte_match": "PROVEN code-body equality under the exported Ghidra function boundaries",
            "mnemonic_match": "STRONGLY_SUPPORTED structural candidate; immediates/operands may differ",
            "name_match": "CANDIDATE only",
            "raw_offset_reuse": "never sufficient by itself",
        },
    }


def parse_offset(text: str) -> int:
    return int(text, 0)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("a", type=Path)
    parser.add_argument("b", type=Path)
    parser.add_argument("-o", "--out", type=Path, required=True)
    parser.add_argument(
        "--anchor",
        action="append",
        default=[],
        type=parse_offset,
        help="image-relative code offset to locate in both builds, e.g. 0xFAAF4",
    )
    args = parser.parse_args()

    result = compare(load(args.a), load(args.b), args.anchor)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
