#!/usr/bin/env python3
"""Fresh-source production driver for D1 activity/entity asset closure.

This driver intentionally consumes only a member catalog generated by the caller in
its current run from the current retail split TAR. It never accepts prior reports,
old exports, known model lists, or historical asset artifacts.

Supported targets:
  crota-stage       exact Crota finale/ultra placement tables -> placed EntitySK roots
  crota-articulated fresh raid/Hive package census -> every articulated EntitySK root
  tower-activity    current Tower Activity graph -> source-typed asset dependency seeds

All targets converge on the same generic source-closed pipeline:
  exact seeds -> recursive entity closure -> models -> material bindings -> selected
  materials -> texture dependencies/export -> every serialized model part/LOD/material
  variant -> animation-capable seed -> every control-selected and bank-only clip.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def load(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8"))


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for b in iter(lambda: f.read(1024 * 1024), b""):
            h.update(b)
    return h.hexdigest()


def run(args: list[str], log: Path | None = None) -> None:
    cmd = [sys.executable, *args]
    print("RUN", " ".join(cmd), flush=True)
    if log is None:
        cp = subprocess.run(cmd, check=False)
    else:
        log.parent.mkdir(parents=True, exist_ok=True)
        with log.open("w", encoding="utf-8") as f:
            cp = subprocess.run(cmd, stdout=f, stderr=subprocess.STDOUT, text=True, check=False)
    if cp.returncode != 0:
        tail = ""
        if log is not None and log.exists():
            lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
            tail = "\n".join(lines[-50:])
        raise RuntimeError(f"command failed rc={cp.returncode}: {' '.join(cmd)}" + (f"\n{tail}" if tail else ""))


def tool(name: str) -> str:
    return str(HERE / name)


def hargs(values: list[str], flag: str = "--seed") -> list[str]:
    out: list[str] = []
    for h in values:
        out += [flag, "0x" + str(h).upper().removeprefix("0X")]
    return out


def seed_target(a, out: Path) -> tuple[list[str], dict]:
    common = [
        "--member-catalog", str(a.member_catalog),
        "--base-url", a.base_url,
        "--part-count", str(a.part_count),
        "--runtime", str(a.runtime),
    ]
    if a.target == "crota-stage":
        p = out / "stage_tables.json"
        run([
            tool("d1_remote_exact_map_data_table_probe.py"),
            "--tag-hash", "0x810978FC", "--tag-hash", "0x8108E2FF",
            *common, "-o", str(p),
        ], out / "logs" / "stage_tables.txt")
        d = load(p)
        if d.get("violation_count") != 0:
            raise ValueError(d.get("violations"))
        roots: list[str] = []
        for t in d.get("tables", []):
            for h in t.get("unique_entity_hashes", []):
                h = h.upper()
                if h not in roots:
                    roots.append(h)
        if not roots:
            raise ValueError("Crota stage tables yielded no EntitySK roots")
        evidence = {
            "seed_mode": "exact_stage_tables",
            "stage_tables": [x.get("tag_hash") for x in d.get("tables", [])],
            "root_count": len(roots),
            "roots": roots,
        }
        (out / "seed_evidence.json").write_text(json.dumps(evidence, indent=2) + "\n")
        return roots, evidence

    if a.target == "crota-articulated":
        p = out / "articulated_census.json"
        run([
            tool("d1_crota_raid_candidate_probe.py"),
            "--raid-package-id", "0x0447", "--raid-package-id", "0x044B", "--raid-package-id", "0x0458",
            "--hive-arch-package-id", "0x0075", "--hive-arch-package-id", "0x0077", "--hive-arch-package-id", "0x075D",
            *common, "-o", str(p),
        ], out / "logs" / "articulated_census.txt")
        d = load(p)
        if int(d.get("error_count", -1)) != 0:
            raise ValueError(d.get("errors", [])[:20])
        roots: list[str] = []
        for row in d.get("articulated_candidates", []):
            h = str(row.get("entity_hash", "")).upper()
            if h and h not in roots:
                roots.append(h)
        if not roots:
            raise ValueError("fresh Crota raid census yielded no articulated EntitySK roots")
        # Names are supplementary exact evidence only; they never select extraction roots.
        try:
            run([
                tool("d1_remote_entity_names_resolve.py"),
                "--candidate-report", str(p),
                "--member-catalog", str(a.member_catalog),
                "--global-package-id", "0x0151", "--global-package-id", "0x0154", "--global-package-id", "0x0155",
                "--global-package-id", "0x0156", "--global-package-id", "0x0157", "--global-package-id", "0x0158",
                "--global-package-id", "0x0169", "--global-package-id", "0x018D", "--global-package-id", "0x01E3",
                "--global-package-id", "0x072B", "--global-package-id", "0x072F", "--global-package-id", "0x0735",
                "--base-url", a.base_url, "--part-count", str(a.part_count), "--runtime", str(a.runtime),
                "-o", str(out / "articulated_names.json"),
            ], out / "logs" / "articulated_names.txt")
        except Exception as ex:
            # Name resolution is not an ownership input. Preserve the failure but do not
            # discard an otherwise exact extraction population.
            (out / "articulated_name_resolution_frontier.txt").write_text(repr(ex) + "\n")
        evidence = {
            "seed_mode": "fresh_raid_and_hive_articulated_census",
            "root_count": len(roots),
            "roots": roots,
            "census_s_entity_count": d.get("s_entity_count"),
            "census_articulated_candidate_count": d.get("articulated_candidate_count"),
            "policy": "Every freshly rediscovered articulated candidate is an extraction root. No historical known/rejected/candidate list filters the population.",
        }
        (out / "seed_evidence.json").write_text(json.dumps(evidence, indent=2) + "\n")
        return roots, evidence

    if a.target == "tower-activity":
        graph = out / "activity_graph"
        run([
            tool("d1_remote_activity_graph_extract.py"),
            "--activity-hash", "80C98019",
            "--activity-name", "map:city_tower:8be28003:root",
            "--activity-class", "80800616",
            *common,
            "--output-dir", str(graph),
        ], out / "logs" / "tower_activity_graph.txt")
        manifest = load(graph / "activity_graph_manifest.json")
        if manifest.get("status") != "D1_REMOTE_ACTIVITY_GRAPH_EXACT":
            raise ValueError(manifest)
        seeds = out / "dependency_seeds.json"
        run([
            tool("d1_activity_asset_dependency_seeds.py"),
            "--graph-dir", str(graph), "-o", str(seeds),
        ], out / "logs" / "tower_dependency_seeds.txt")
        d = load(seeds)
        if d.get("status") != "D1_ACTIVITY_ASSET_DEPENDENCY_SEEDS_EXACT":
            raise ValueError(d.get("violations"))
        roots = [str(h).upper() for h in d.get("closure_seed_hashes", [])]
        if not roots:
            raise ValueError("Tower Activity yielded no closure seeds")
        evidence = {
            "seed_mode": "fresh_activity_graph_typed_asset_seeds",
            "root_count": len(roots),
            "roots": roots,
            "activity_graph_counts": manifest.get("counts"),
            "seed_group_counts": d.get("counts"),
        }
        (out / "seed_evidence.json").write_text(json.dumps(evidence, indent=2) + "\n")
        return roots, evidence

    raise ValueError(a.target)


def build_geometry_catalog(member_catalog: Path, model_plan: Path, visual: Path, output: Path) -> list[str]:
    sys.path.insert(0, str(HERE))
    from d1_investment_arrangement_probe import filehash_pkg_index
    full = load(member_catalog)
    p = load(model_plan)
    v = load(visual)
    hashes = list(p.get("model_hashes", [])) + list(v.get("buffer_headers", [])) + list(v.get("backing_payload_hashes", []))
    keys = sorted({f"{filehash_pkg_index(int(h,16))[0]:04X}" for h in hashes})
    missing = [k for k in keys if k not in full.get("families", {})]
    if missing:
        raise ValueError(f"geometry package families absent from fresh catalog: {missing}")
    o = dict(full)
    o["families"] = {k: full["families"][k] for k in keys}
    o["package_family_count"] = len(keys)
    o["scope"] = "same_run_target_specific_geometry_dependencies"
    o["policy"] = "Subset derived only from current-run model/buffer FileHashes; package filtering is transport optimization, not semantic ownership."
    output.write_text(json.dumps(o, indent=2) + "\n")
    return keys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=("crota-stage", "crota-articulated", "tower-activity"), required=True)
    ap.add_argument("--member-catalog", type=Path, required=True)
    ap.add_argument("--fresh-source-manifest", type=Path, required=True)
    ap.add_argument("--base-url", required=True)
    ap.add_argument("--part-count", type=int, default=10)
    ap.add_argument("--runtime", type=Path, required=True)
    ap.add_argument("--parser-root", type=Path, required=True)
    ap.add_argument("--out-dir", type=Path, required=True)
    a = ap.parse_args()

    out = a.out_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "logs").mkdir(exist_ok=True)
    (out / "textures").mkdir(exist_ok=True)
    (out / "models_all_parts").mkdir(exist_ok=True)
    (out / "animation_bank").mkdir(exist_ok=True)

    source = load(a.fresh_source_manifest)
    if source.get("status") != "D1_FRESH_SOURCE_INDEX_COMPLETE":
        raise ValueError("fresh source manifest not complete")
    if source.get("github_sha") != os.environ.get("GITHUB_SHA"):
        raise ValueError(f"fresh source checkout mismatch {source.get('github_sha')} != {os.environ.get('GITHUB_SHA')}")
    if sha256(a.member_catalog) != source.get("member_catalog_sha256"):
        raise ValueError("fresh member catalog SHA mismatch")

    roots, seed_evidence = seed_target(a, out)
    common = [
        "--member-catalog", str(a.member_catalog),
        "--base-url", a.base_url,
        "--part-count", str(a.part_count),
        "--runtime", str(a.runtime),
    ]

    closure = out / "entity_closure.json"
    run([
        tool("d1_remote_entity_dependency_closure_universal.py"),
        *hargs(roots), *common,
        "--max-depth", "6", "--max-nodes", "50000", "-o", str(closure),
    ], out / "logs" / "entity_closure.txt")
    cd = load(closure)
    if cd.get("status") != "D1_ENTITY_DEPENDENCY_CLOSURE_COMPLETE" or cd.get("truncated") or cd.get("violations"):
        raise ValueError("entity closure incomplete")

    model_plan = out / "model_plan.json"
    visual = out / "visual_closure.json"
    bindings = out / "material_bindings.json"
    selected = out / "selected_material_plan.json"
    material_deps = out / "material_dependencies.json"
    run([tool("d1_activity_entity_model_plan.py"), "--entity-closure", str(closure), "-o", str(model_plan)], out / "logs" / "model_plan.txt")
    run([tool("d1_remote_activity_model_visual_dependency_closure.py"), "--model-plan", str(model_plan), *common, "-o", str(visual)], out / "logs" / "visual_closure.txt")
    run([tool("d1_remote_activity_model_material_bindings.py"), "--entity-closure", str(closure), *common, "-o", str(bindings)], out / "logs" / "material_bindings.txt")
    run([tool("d1_activity_selected_material_plan.py"), "--visual-closure", str(visual), "--material-bindings", str(bindings), "-o", str(selected)], out / "logs" / "selected_materials.txt")
    run([tool("d1_remote_activity_material_dependency_closure.py"), "--selected-material-plan", str(selected), *common, "-o", str(material_deps)], out / "logs" / "material_dependencies.txt")
    run([tool("d1_remote_activity_texture_export.py"), "--material-closure", str(material_deps), *common, "--out-dir", str(out / "textures")], out / "logs" / "texture_export.txt")

    statuses = {
        model_plan: "D1_ACTIVITY_ENTITY_MODEL_PLAN_COMPLETE",
        visual: "D1_REMOTE_ACTIVITY_MODEL_VISUAL_DEPENDENCY_CLOSURE_COMPLETE",
        bindings: "D1_REMOTE_ACTIVITY_MODEL_MATERIAL_BINDINGS_COMPLETE",
        selected: "D1_ACTIVITY_SELECTED_MATERIAL_PLAN_COMPLETE",
        material_deps: "D1_REMOTE_ACTIVITY_MATERIAL_DEPENDENCY_CLOSURE_COMPLETE",
    }
    for p, status in statuses.items():
        d = load(p)
        if d.get("status") != status or d.get("violations"):
            raise ValueError(f"{p.name}: {d.get('status')} / {d.get('violations')}")
    tex_manifest = load(out / "textures" / "texture_export_manifest.json")
    if tex_manifest.get("status") != "D1_REMOTE_ACTIVITY_TEXTURE_EXPORT_COMPLETE" or tex_manifest.get("violations"):
        raise ValueError("texture export incomplete")

    geom_cat = out / "geometry_member_catalog.json"
    geometry_packages = build_geometry_catalog(a.member_catalog, model_plan, visual, geom_cat)
    all_parts = out / "all_parts_export.json"
    mp = load(model_plan)
    if int(mp.get("model_count", 0)) > 0:
        run([
            tool("d1_remote_model_export_all_parts.py"),
            "--model-plan", str(model_plan),
            "--member-catalog", str(geom_cat),
            "--base-url", a.base_url, "--part-count", str(a.part_count), "--runtime", str(a.runtime),
            "--out-dir", str(out / "models_all_parts"), "-o", str(all_parts),
        ], out / "logs" / "all_parts_export.txt")
        gd = load(all_parts)
        if gd.get("status") != "D1_REMOTE_MODEL_EXPORT_ALL_PARTS_COMPLETE":
            raise ValueError(gd)
    else:
        gd = {
            "schema": "d1_remote_model_export_all_parts/v1",
            "status": "D1_REMOTE_MODEL_EXPORT_ALL_PARTS_COMPLETE",
            "model_count": 0,
            "drawable_serialized_part_variant_count": 0,
            "triangle_count_with_variants": 0,
            "catalog_package_ids": geometry_packages,
            "models": [],
            "source_closed_empty_model_population": True,
        }
        all_parts.write_text(json.dumps(gd, indent=2) + "\n")

    anim_seed = out / "animation_seed.json"
    anim_options = out / "animation_options.json"
    anim_bank = out / "animation_bank_export.json"
    run([tool("d1_activity_actor_animation_seed.py"), "--entity-closure", str(closure), "-o", str(anim_seed)], out / "logs" / "animation_seed.txt")
    run([
        tool("d1_remote_spawned_actor_animation_options_v3.py"),
        "--seed", str(anim_seed), *common, "--parser-root", str(a.parser_root), "-o", str(anim_options),
    ], out / "logs" / "animation_options.txt")
    run([
        tool("d1_remote_animation_bank_export.py"),
        "--animation-options", str(anim_options), *common, "--parser-root", str(a.parser_root),
        "--out-dir", str(out / "animation_bank"), "-o", str(anim_bank),
    ], out / "logs" / "animation_bank.txt")
    ad = load(anim_options)
    bd = load(anim_bank)
    if ad.get("status") != "D1_ACTIVITY_ACTOR_ANIMATION_OPTIONS_COMPLETE" or ad.get("violation_count") or ad.get("frontier_count") or ad.get("retarget_pair_failure_count"):
        raise ValueError("animation options incomplete")
    if bd.get("status") != "D1_REMOTE_ANIMATION_BANK_EXPORT_COMPLETE" or bd.get("violations"):
        raise ValueError("animation bank export incomplete")

    sd = load(selected)
    td = load(material_deps)
    manifest = {
        "schema": "d1_fresh_activity_asset_target/v1",
        "status": "D1_FRESH_ACTIVITY_ASSET_TARGET_COMPLETE",
        "target": a.target,
        "source": source,
        "seed_evidence": seed_evidence,
        "entity_closure": {
            "node_count": cd.get("node_count"),
            "edge_count": cd.get("edge_count"),
            "typed_edge_count": cd.get("typed_edge_count"),
            "untyped_edge_count": cd.get("untyped_edge_count"),
            "articulated_entity_count": len(cd.get("articulated_entities", [])),
        },
        "model_count": mp.get("model_count", 0),
        "geometry_package_ids": geometry_packages,
        "serialized_drawable_part_variant_count": gd.get("drawable_serialized_part_variant_count", 0),
        "triangle_count_with_variants": gd.get("triangle_count_with_variants", 0),
        "selected_material_count": sd.get("unique_material_count", 0),
        "texture_count": td.get("unique_texture_count", 0),
        "animation_capable_entity_count": load(anim_seed).get("animation_capable_entity_count", 0),
        "animation_control_count": ad.get("unique_control_count", 0),
        "selector_selected_clip_count": ad.get("unique_selector_selected_clip_count", 0),
        "animation_list_bank_clip_count": ad.get("unique_animation_list_clip_count", 0),
        "raw_animation_clip_count": bd.get("exported_raw_clip_count", 0),
        "retarget_pair_success_count": ad.get("retarget_pair_success_count", 0),
        "retarget_pair_failure_count": ad.get("retarget_pair_failure_count", 0),
        "policy": (
            "All target seeds and every payload are derived/reopened from current retail source in this run with the "
            "current checked-out tools. No prior extraction, prior report, old GLB, old texture library, old animation "
            "bank, historical candidate list, or cross-run artifact is an input. Exact empty populations remain empty."
        ),
    }
    (out / "PRODUCTION_MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
